---
- name: Install and configure Zabbix agent on RHEL
  hosts: all
  become: true

  vars:
    zabbix_server_ip: "192.168.0.177"    # <-- Change to your real Zabbix server IP
    zabbix_agent_version: "6.0"           # <-- LTS version at time of writing

  tasks:

    - name: Install Zabbix repository
      yum:
        name: "https://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/rhel/8/x86_64/zabbix-release-{{ zabbix_agent_version }}-1.el8.noarch.rpm"
        state: present

    - name: Install Zabbix agent
      yum:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"
        backup: yes

    - name: Configure Zabbix agent (Active Server)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_ip }}"
        backup: yes

    - name: Configure Zabbix agent hostname (Optional)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"
        backup: yes

    - name: Enable and start zabbix-agent service
      systemd:
        name: zabbix-agent
        enabled: yes
        state: started
