---
- name: Fetch index.html from node1
  hosts: node1
  tasks:
    - name: Fetch file from node1
      fetch:
        src: /var/www/html/index.html
        dest: /tmp/index.html
        flat: yes

- name: Copy index.html to node2
  hosts: node2
  tasks:
    - name: Copy file to node2
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html

- name: Start the services at DR
  hosts: node1
  tasks:
   - name: firewalld enabled and running
     service:
      name: firewalld
      enabled: true
      state: started
     delegate_to: node2      
   - name: firewalld permits http service
     firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
     delegate_to: node2
   - name: httpd enabled and running
     service:
      name: httpd
      enabled: true
      state: started
     delegate_to: node2
