---
- name: Create an EC2 instance
  hosts: all
  become: true
  gather_facts: False
  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "HDFC_Demo_Instance"
        region: "us-east-1"
        key_name: ansible
        vpc_subnet_id: subnet-0f258d835b99f4f8c
        instance_type: t2.micro
        security_group: sg-09c9ce9090a9d72df
        network:
          assign_public_ip: true
        image_id: ami-0583d8c7a9c35822c
        tags:
          Environment: Testing
      register: ec2

    - name: Print new instance ID
      debug:
        msg: "EC2 instance ID is {{ ec2.instance_ids[0] }}"
