
---
- name: Create an EC2 instance
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  gather_facts: False
  tasks:
    - name: create a VPC
      amazon.aws.ec2_vpc_net:
        name: Module_dev2
        cidr_block: 10.0.0.0/16
        ipv6_cidr: true
        region: us-east-1
        tenancy: dedicated
      register: vpc
    - name: Create subnet
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: 10.0.0.0/28
        region: us-east-1
      register: subnet

    - name: Create Security Group
      ec2_group:
        state: present
        name: demo-security-group
        description: "demo-security-group"
        vpc_id: "{{ vpc.vpc.id }}"
        region: us-east-1
        rules:
          - proto: 80
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: "allow all on port 80"
      register: security_group
