- name: Check if a Configuration file for retail application exists
  hosts: all  
  tasks:
    - name: Check if the file exists
      ansible.builtin.stat:
        path: /home/ec2-user/apps/retail 
      register: file_check

    - name: Display message if file exists
      ansible.builtin.debug:
        msg: "Configuration file for retail application exists"
      when: file_check.stat.exists

    - name: Display message if file does not exist
      ansible.builtin.debug:
        msg: "Configuration file for retail application  does not exist."
      when: not file_check.stat.exists
