---
- hosts: all
  gather_facts: no
  tasks:
    - name: "Only show diff between Pre Patching and Post Patching config files" 
      shell: diff -w /tmp/prepatch.txt /tmp/postpatch.txt > /tmp/config_drift
      ignore_errors: yes
