---
- name: Prechecks before reboot
  hosts: "{{ ip }}"
  tasks:
    # copy the Precheck to the NAs drive 
    - name: Give execute permission to precheck  script
     shell: chmod 777 precheck.sh
     args:
       chdir: /root
   - name: Execute Precheck script
     shell: ./precheck.sh
     args:
       chdir: /root
     #ignore_errors: yes
   - name: Copy the output of the precheck script to the defined target
     shell: cp /tmp/rebootprecheck.txt /var/log/reboot_precheck_`date +%Y_%m_%d_%H_%M`_.txt
   - name: Display output location of the precheck script
     shell: echo The output location of the precheck script is /var/log/reboot_precheck_`date +%Y_%m_%d_%H_%M`_.txt
