---
- hosts: all
  tasks:
  - user:
     name: johnd
     comment: "John Doe"
     uid: 1040
     password: rachna | password_hash('sha512')
  - name: Change file ownership, group and permissions
    file:
     path: /tmp/rach
     owner: johnd
     mode: '0644'
