---
- hosts: all
  tasks:
    - name: c1
      block:
        - name: check 
          shell: cat /root/compliance.csv |grep 1000309 |grep "Non Compliant"
          register: result
        - name: check 1
          shell: cat /root/compliance.csv |grep 1000309 |grep "Non Compliant"|awk -F, '{print $4}'
          register: result1
        - name: debug var
          debug:
            var: result1
        - name: check 
          set_fact: 
            h: "{{ result1.stdout_lines }}"     
        - name: remediate
          debug:
            var: h
          delegate_to: "{{ item }}" 
          with_items: "{{ groups.h }}"
          
   
