---
- hosts: all
  tasks:
    - name: 5.1.4
      block:
        - name: Check the severity for plugin 1000164 
          shell: cat /root/compliance.csv |grep 1000164 |grep "Non Compliant"|awk -F, '{print $5}'
          register: result1
        - name: debug host
          debug:
            var: result1
        - name: check 
          set_fact: 
            h: "{{ result1.stdout_lines }}" 
          when: result1.stdout_lines != []
        - name: 5.1.4 Ensure permissions on /etc/cron.daily are configured
          debug:
            var: h
          delegate_to: h
          when: result1.stdout_lines != []
          
   
