---
- hosts: all
  tasks:
    - name: c1
      block:
        - name: check 
          shell: cat /root/compliance.csv |grep 1000309 |grep "Non Compliant"
          register: result
        - name: check 
          debug: 
            var: result
   
