---
- name: Deploy JBoss EAP/WildFly on RHEL 8.7
  hosts: all
  become: yes
  vars:
    jboss_version: "27.0.1.Final"   # Example WildFly version (adjust if using EAP)
    jboss_install_dir: "/opt/jboss"
    jboss_user: "jboss"
    jboss_group: "jboss"
    jboss_home: "/opt/jboss/wildfly-{{ jboss_version }}"
    jboss_download_url: "https://github.com/wildfly/wildfly/releases/download/{{ jboss_version }}/wildfly-{{ jboss_version }}.tar.gz"

  tasks:
    - name: Install required packages
      ansible.builtin.yum:
        name:
          - java-11-openjdk-headless
          - unzip
          - tar
        state: present

    - name: Create jboss group
      ansible.builtin.group:
        name: "{{ jboss_group }}"
        state: present

    - name: Create jboss user
      ansible.builtin.user:
        name: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
        home: "{{ jboss_install_dir }}"
        shell: /bin/bash
        state: present

    - name: Create installation directory
      ansible.builtin.file:
        path: "{{ jboss_install_dir }}"
        state: directory
        owner: "{{ jboss_user }}"
        group: "{{ jboss_group }}"
        mode: '0755'

    - name: Download JBoss (WildFly)
      ansible.builtin.get_url:
        url: "{{ jboss_download_url }}"
        dest: "/tmp/wildfly-{{ jboss_version }}.tar.gz"
        mode: '0644'

    - name: Extract JBoss
      ansible.builtin.unarchive:
        src: "/tmp/wildfly-{{ jboss_version }}.tar.gz"
        dest: "{{ jboss_install_dir }}"
        remote_src: yes
        owner: "{{ jboss_user }}"
        group: "{{ jboss_group }}"

    - name: Symlink JBoss to /opt/jboss/latest
      ansible.builtin.file:
        src: "{{ jboss_home }}"
        dest: "{{ jboss_install_dir }}/latest"
        state: link
        force: yes

    - name: Create systemd service for JBoss
      ansible.builtin.copy:
        dest: /etc/systemd/system/jboss.service
        content: |
          [Unit]
          Description=JBoss Application Server
          After=network.target

          [Service]
          Type=simple
          User={{ jboss_user }}
          Group={{ jboss_group }}
          ExecStart={{ jboss_install_dir }}/latest/bin/standalone.sh -b=0.0.0.0
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify: Restart JBoss

  handlers:
    - name: Restart JBoss
      ansible.builtin.systemd:
        name: jboss
        state: restarted
        enabled: yes
