---
- name: capture iops
  hosts: all
  tasks:
    - name: Get IOPS data from iostat
      ansible.builtin.shell: "iostat -dx 1 2 | awk '/nvme0n1/ {print $2}' | tail -n +1 | head -n 1"
      register: iops_result
      changed_when: false
