---
- name: Password Policy Violation Check
  hosts: all
  tasks:
   - name: Check the policy
     shell: "grep -r '^minlen = 9' /etc/security/pwquality.conf"
     register: grep_output
     ignore_errors: yes
   - debug:
      msg: "########     Password policy is violated      #######"
     when: grep_output is failed
     ignore_errors: yes
   - debug:
      msg: "######     Password policy is in compliance     ######"
     when: grep_output is succeeded
     ignore_errors: yes
