---
- name: Precheck server
  hosts: "{{ host }}"
  tasks:
   - name: Give execute permission to precheck  script
     shell: chmod 777 /home/ec2-user/precheck.sh
   - name: Precheck
     shell: ./precheck.sh
     args:
       chdir: /home/ec2-user
     ignore_errors: yes
