---
- name: Install the pre-requisite packages
  hosts: "{{ ip }}"
  tasks: 
   - name: Install sysstat package
     yum:
       name: sysstat
       state: latest
     ignore_errors: yes
   - name: Install net-tools package
     yum:
       name: net-tools
       state: latest
     ignore_errors: yes
   - name: Install device-mapper-multipath package
     yum:
       name: device-mapper-multipath
       state: latest
     ignore_errors: yes
   - name: Install iproute-tc package
     yum:
       name: iproute-tc
       state: latest
     ignore_errors: yes
